platform:ios,'11.0'
use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true

target 'RxIGListKit_Example' do
  pod 'RxIGListKit', :path => '../'

  target 'RxIGListKit_Tests' do
    inherit! :search_paths

    
  end
end
